// frontend/src/lib/Header.svelte
<script>
</script>

<div
    class="fixed left-0 top-0 z-50 bg-white/90 backdrop-blur w-full py-6 px-8 flex flex-col sm:flex-row items-center gap-4 shadow-sm"
>
    <div class="flex items-center flex-1">
        <svg
            xmlns="http://www.w3.org/2000/svg"
            viewBox="0 0 24 24"
            fill="currentColor"
            class="w-8 h-8 text-blue-500"
        >
            <path
                d="M18.375 2.25c-1.035 0-1.875.84-1.875 1.875v15.75c0 1.035.84 1.875 1.875 1.875h.75c1.035 0 1.875-.84 1.875-1.875V4.125c0-1.036-.84-1.875-1.875-1.875h-.75ZM9.75 8.625c0-1.036.84-1.875 1.875-1.875h.75c1.036 0 1.875.84 1.875 1.875v11.25c0 1.035-.84 1.875-1.875 1.875h-.75a1.875 1.875 0 0 1-1.875-1.875V8.625ZM3 13.125c0-1.036.84-1.875 1.875-1.875h.75c1.036 0 1.875.84 1.875 1.875v6.75c0 1.035-.84 1.875-1.875 1.875h-.75A1.875 1.875 0 0 1 3 19.875v-6.75Z"
            />
        </svg>
        <div class="text-2xl ml-1 font-bold">Astra Dashboard</div>
    </div>
</div>

// frontend/src/components/Header.tsx
import { ChartBarIcon } from '@heroicons/react/24/solid'


export default function Header() {
    return (
        <div className="fixed z-50 bg-white w-full py-6 px-8 flex flex-col sm:flex-row items-center gap-4 shadow-sm">
            <div className="flex items-center flex-1">
                <ChartBarIcon className="h-8 w-8 text-blue-500" />
                {/* <IconBallTennis aria-hidden="true" /> */}
                <div className="text-2xl ml-1 font-bold">
                    Astra Dashboard
                </div>
            </div>
        </div>
    );
}
